In [9]:
import pandas as pd
#One hot encode UR8_2022 
df = pd.read_parquet('/PHI_conf/VaccineUptake/Analysts/Vay/vaccinate_uptake_ML_analysis/vaccine_data/master_data/cohort_df_merged.parquet')

df.info()

df

<class 'pandas.core.frame.DataFrame'>
Index: 9169749 entries, 0 to 9170518
Data columns (total 6 columns):
 #   Column                      Dtype
---  ------                      -----
 0   cohort_group_ML_analysis    object
 1   patient_sex                 int64
 2   patient_age                 int32
 3   SIMD_quintile               int32
 4   UR8_2022                    int32
 5   attended_vaccination_event  int64
dtypes: int32(3), int64(2), object(1)
memory usage: 384.8+ MB

,cohort_group_ML_analysis,patient_sex,patient_age,SIMD_quintile,UR8_2022,attended_vaccination_event
0,AGE_50_TO_64,1,63,4,6,1
1,AGE_50_TO_64,0,64,4,1,1
2,AGE_50_TO_64,1,63,1,3,1
3,AGE_50_TO_64,0,64,4,6,1
4,AGE_50_TO_64,0,63,5,2,1
...,...,...,...,...,...,...
9170514,WEAKENED_IMMUNE_SYSTEM,1,85,4,6,1
9170515,WEAKENED_IMMUNE_SYSTEM,0,81,1,2,1
9170516,WEAKENED_IMMUNE_SYSTEM,1,88,5,3,0
9170517,WEAKENED_IMMUNE_SYSTEM,1,68,1,1,0
9170518,WEAKENED_IMMUNE_SYSTEM,1,86,2,1,0

In [10]:


# One-hot encode UR8_2022
ur8_encoded = pd.get_dummies(df['UR8_2022'], prefix='UR8_2022').astype(int)

# Find the index of SIMD_quintile
simd_index = df.columns.get_loc('SIMD_quintile')

# Split the DataFrame into parts
before = df.iloc[:, :simd_index + 1]
after = df.iloc[:, simd_index + 1:].drop(columns=['UR8_2022'])

# Concatenate with one-hot columns in the middle
df_final = pd.concat([before, ur8_encoded, after], axis=1)

df_final

,cohort_group_ML_analysis,patient_sex,patient_age,SIMD_quintile,UR8_2022_1,UR8_2022_2,UR8_2022_3,UR8_2022_4,UR8_2022_5,UR8_2022_6,UR8_2022_7,UR8_2022_8,attended_vaccination_event
0,AGE_50_TO_64,1,63,4,0,0,0,0,0,1,0,0,1
1,AGE_50_TO_64,0,64,4,1,0,0,0,0,0,0,0,1
2,AGE_50_TO_64,1,63,1,0,0,1,0,0,0,0,0,1
3,AGE_50_TO_64,0,64,4,0,0,0,0,0,1,0,0,1
4,AGE_50_TO_64,0,63,5,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9170514,WEAKENED_IMMUNE_SYSTEM,1,85,4,0,0,0,0,0,1,0,0,1
9170515,WEAKENED_IMMUNE_SYSTEM,0,81,1,0,1,0,0,0,0,0,0,1
9170516,WEAKENED_IMMUNE_SYSTEM,1,88,5,0,0,1,0,0,0,0,0,0
9170517,WEAKENED_IMMUNE_SYSTEM,1,68,1,1,0,0,0,0,0,0,0,0
9170518,WEAKENED_IMMUNE_SYSTEM,1,86,2,1,0,0,0,0,0,0,0,0

In [11]:
pd.options.display.float_format = '{:,.4f}'.format
df_final.describe()

,patient_sex,patient_age,SIMD_quintile,UR8_2022_1,UR8_2022_2,UR8_2022_3,UR8_2022_4,UR8_2022_5,UR8_2022_6,UR8_2022_7,UR8_2022_8,attended_vaccination_event
count,"9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000","9,169,749.0000"
mean,0.5525,58.5074,2.9640,0.3786,0.3149,0.1008,0.0061,0.0153,0.1326,0.0218,0.0300,0.5470
std,0.4972,14.6035,1.3970,0.4850,0.4645,0.3011,0.0776,0.1226,0.3391,0.1460,0.1705,0.4978
min,0.0000,18.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.0000,52.0000,2.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,1.0000,59.0000,3.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
75%,1.0000,67.0000,4.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
max,1.0000,115.0000,5.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [12]:

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9169749 entries, 0 to 9170518
Data columns (total 13 columns):
 #   Column                      Dtype
---  ------                      -----
 0   cohort_group_ML_analysis    object
 1   patient_sex                 int64
 2   patient_age                 int32
 3   SIMD_quintile               int32
 4   UR8_2022_1                  int64
 5   UR8_2022_2                  int64
 6   UR8_2022_3                  int64
 7   UR8_2022_4                  int64
 8   UR8_2022_5                  int64
 9   UR8_2022_6                  int64
 10  UR8_2022_7                  int64
 11  UR8_2022_8                  int64
 12  attended_vaccination_event  int64
dtypes: int32(2), int64(10), object(1)
memory usage: 909.5+ MB

In [13]:
df_final.to_parquet("/PHI_conf/VaccineUptake/Analysts/Vay/vaccinate_uptake_ML_analysis/vaccine_data/master_data/cohort_df_merged_UR8_encoded.parquet")